BLOCK_SITE:
- https://www.oliverkou.top/
- https://blog.xiaohack.org/
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://dusays.com/friends/
  theme: volantis
MAX_POSTS_NUM: 50
OUTDATE_CLEAN: 3000
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u5C0F\u7B80\u535A\u5BA2"
    - https://blog.ideaopen.cn/
    - https://bu.dusays.com/2022/05/31/6295d1906b264.jpg
    - index.php/feed/
  - - "\u6C90\u5370\u5C0F\u7AD9"
    - https://c.undf.top/
    - https://c.undf.top/icon/android-chrome-144x144.png
    - atom.xml
  - - "\u53F6\u5F00\u535A\u5BA2"
    - https://qq.md/
    - https://xn--qpru0x.cn/tx.png
    - feed/
  - - SeerSu
    - https://seersu.me/
    - https://seersu.me/favicon/avatar.jpg
    - index.xml
  - - "\u897F\u74DC\u649E\u5730\u7403"
    - https://www.bio-w.cn/
    - https://bu.dusays.com/2022/10/17/634d313602a1e.png
    - atom.xml
  - - "\u9189\u91CC"
    - https://202271.xyz/
    - https://bu.dusays.com/2022/12/05/638dcd9f515d3.png
    - atom.xml
  - - "Cold\u2019blog"
    - https://www.coldyun.cn/
    - https://ucdn.coldyun.cn/handsome/handsome8.00/assets/img/tou.jpg
    - feed/
  - - "Rose\u535A\u5BA2"
    - https://rosebk.cn/
    - https://cravatar.cn/avatar/5dbff385854d7717d26a267e1c01fbbc?d=mp&s=80
    - feed/
  - - "\u6DC7\u4E91\u535A\u5BA2"
    - https://www.pengqi.club/
    - https://bu.dusays.com/2023/03/03/6401afb464570.png
    - feed/
  - - "fred \u968F\u7B14"
    - https://alialili.cn/
    - https://bu.dusays.com/2022/07/08/62c7ad29019cb.webp
    - atom.xml
  - - "\u957F\u8857\u77ED\u68A6"
    - https://wangyunzi.com/
    - https://blog.wangyunzi.com/article/avatar.jpg
    - atom.xml
  - - "\u4ECA\u5915\u4F55\u5915\u516E"
    - https://www.ginc.site/
    - https://cdn.jsdelivr.net/gh/lyboy-wp/jscdn/img/favicon.ico
    - feed/
  - - "\u94A7\u8A00\u6781\u5BA2"
    - https://www.jinjun.top/
    - https://www.jinjun.top/img/avatar.jpg
    - feed/
  - - "\u4E03\u4E91\u2019s Blog"
    - https://www.zets.cn/
    - https://q.qlogo.cn/g?b=sdk&k=UeVu6eVo5SdL2Eu7PiczvTw&s=640
    - feed/
  - - "\u661F\u65E5\u8BED"
    - https://weekdaycare.cn/
    - https://weekdaycare.cn/asset/avatar.svg
    - atom.xml
  - - "\u897F\u74DC\u649E\u5730\u7403"
    - https://www.bio-w.cn/
    - https://bu.dusays.com/2022/10/17/634d313602a1e.png
    - atom.xml
  - - "\u6EE1\u5FC3Hrn"
    - https://blog.lovelu.top/
    - https://bu.dusays.com/2022/12/15/639a81c28f3bc.png
    - atom.xml
  - - "\u4E03\u9CC4\u306E\u5B66\u4E60\u683C"
    - https://blog.gmcj0816.top/
    - https://blog.gmcj0816.top/img/SeriousWission_TouXiangPic.jpg
    - atom.xml
  - - "\u6781\u5BA2\u90CE"
    - https://ximfem.asia/
    - https://ximfem.asia/img/jkl1.png
    - atom.xml
