BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://dusays.com/friends/
  theme: volantis
MAX_POSTS_NUM: 50
OUTDATE_CLEAN: 3000
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - Blogin
    - https://2dogz.cn/
    - https://bu.dusays.com/2020/11/13/b54215c2293a9.jpg
    - rss-feed/
  - - "\u5C0F\u7B80\u535A\u5BA2"
    - https://blog.ideaopen.cn/
    - https://bu.dusays.com/2022/05/31/6295d1906b264.jpg
    - index.php/feed/
  - - Hello Lin
    - https://www.hellolin.cn/
    - https://bu.dusays.com/2022/08/02/62e8d85fa20f5.png
    - feed/
